### ISSUE TITLE
Support `if` clauses in `depends_components` and `depends_filepatterns`

### ISSUE THREAD

**Issue by hfudev** [espressif/idf-build-apps#105]
For example

```yaml
folder_foo:
  depends_components:
    - if: IDF_VERSION == "5.2.0":
      components: ["esp_eth"]
    - if: IDF_VERSION == "5.3.0":
      components: ["esp_wifi"]
    - components: ["esp_eth", "esp_wifi"]
```

To keep the similarity with others, here the folder rule should also apply the first matched `if` statement. but on extra, we support one more "default" switch case.

explanation:

- if idf 5.2.0, depends_components: esp_eth
- if idf 5.3.0, depends_components: esp_wifi
- by default (other cases), depends_components: esp_eth, esp_wifi

`depends_filepatterns` should be something alike.

**Comment by ydc-0** [comment]
There is another usage case, can you consider support:

```
examples/wifi:   # or anchor
  base_depends_components:
    esp_hw_support
    esp_rom
    esp_wifi

examples/wifi/coexist:
  add_components:
    esp_coex
```

**Comment by hfudev** [comment]
@ydc-0 I think we should avoid adding more and more keywords. Maybe we can support a new feature that enhance the original yaml? That could help make the yaml anchor more useful.

For example

```yaml
.base_depends_components: &base-depends-components
  depends_components:
    - esp_hw_support
    - esp_rom
    - esp_wifi
  
examples/wifi/coexist:
  <<: *base-depends-components
  depends_components+:
    - esp_coex
  depends_components-:
    - esp_rom
```

Will be interpreted into

```
examples/wifi/coexist:
  depends_components:
    - esp_hw_support
    - esp_wifi
    - esp_coex
```

The `+` and `-` here could be used on all keywords that could be used as a dict key, like `depends_components`, `depends_filepatterns`, `disable`, `enable`, ...

Creating another ticket for this feature.

**Comment by hfudev** [comment]
This use case is more practical.

Assume we're testing an ota related example, one config `sdkconfig.eth` is using ethernet, another config `sdkconfig.wifi` is using wifi

```yaml
folder_foo:
  depends_components:
    - if: CONFIG_NAME == "eth"
      components: ["esp_eth"]
    - if: CONFIG_NAME == "wifi":
      components: ["esp_wifi"]
```
