### ISSUE TITLE
Enhance YAML Parser (RDT-630)

### ISSUE THREAD

**Issue by hfudev** [espressif/idf-build-apps#106]
The vanilla yaml does not support reuse arrays, the merge only happens with different keys.

Support `+` and `-` as postfixes to reuse arrays.

```yaml
.base_depends_components: &base-depends-components
  depends_components:
    - esp_hw_support
    - esp_rom
    - esp_wifi
  
examples/wifi/coexist:
  <<: *base-depends-components
  depends_components+:
    - esp_coex
  depends_components-:
    - esp_rom
```

Will be interpreted into

```yaml
examples/wifi/coexist:
  depends_components:
    - esp_hw_support
    - esp_wifi
    - esp_coex
```

The `+` and `-` here could be used on all keywords that could be used as a dict key, like `depends_components`, `depends_filepatterns`, `disable`, `enable`, ...

The way that how items defined in the `+` and `-` matching with the original ones must be flexible. For example, in each if-clause defined under the `enable` key, we support three keywords: `if`, `temp`, `reason`. `if` should be the match key here.

For example,

```yaml
.base: &base
  enable:
    - if: IDF_VERSION == "5.2.0"
    - if: IDF_VERSION == "5.3.0"

foo:
  <<: *base
  enable+:
    - if: IDF_VERSION == "5.2.0"
      temp: true  # <-- This line should not be added, since the `if` is the matching key, and the `if` statement is the same.
    - if: IDF_VERSION == "5.4.0"
      reason: bar
```

Will be interpreted into

```yaml
foo:
  enable:
    - if: IDF_VERSION == "5.2.0"
    - if: IDF_VERSION == "5.3.0"
    - if: IDF_VERSION == "5.4.0"
      reason: bar
```

Create a subpackage `idf_build_apps.yaml` for this new yaml parser. This could be reused elsewhere.
