### ISSUE TITLE
Support CONFIG_FILENAME in manifest file (RDT-438)

### ISSUE THREAD

**Issue by hfudev** [espressif/idf-build-apps#38]
This is to help the use case that some config file only applies to specific targets.

For example, psram is only supported by those targets whose soc caps header has `SOC_SPIRAM_SUPPORTED` (esp32, esp32s2, and esp32s3)

we could write

- sdkconfig.ci.psram_release (empty file)
  - sdkconfig.ci.psram_release.esp32 (target-specific config items)
  - sdkconfig.ci.psram_release.esp32s2 (...)
  - sdkconfig.ci.psram_release.esp32s3 (...)

The app will be built with all targets in the CI, since the psram_release file is empty.

After this feature got implemented, the manifest file will look like:

```yaml
<this folder>:
  rules:
    - if: CONFIG_FILENAME == "psram_release" and SOC_SPIRAM_SUPORTED == 1
```

and it will only be built with esp32, esp32s2, and esp32s3
