### ISSUE TITLE
Support Keyword `IDF_VERSION_MAJOR`, `IDF_VERSION_MINOR`, `IDF_VERSION_PATCH` (RDT-403)

### ISSUE THREAD

**Issue by hfudev** [espressif/idf-build-apps#8]
This could be used in the if clauses defined in the manifest file. These values are integer.

some repo might have different build rules set for different ESP-IDF branch

Example:

```yaml
examples:
  enable:
    - if: IDF_VERSION_MAJOR == 4 and IDF_VERSION_MINOR in [1, 2]  # will only build & test on 4.1 and 4.2
```
Warnings:
- the rule would take effect if any of the if clauses matches.
- all operators are binary operator. use nested parentheses for complicated use case.
