### ISSUE TITLE
Root Config File to Control Build Test Rules Default Values

### ISSUE THREAD

**Issue by hfudev** [espressif/idf-build-apps#98]
For now the default running targets for build & test are all defined in one place, `--default-build-targets`, could be more flexible with

```yaml
default_rules:
  esp32: true  # build and test
  esp32h2:
    build: true
    test: false
  # test: true and build: false is invalid...
  # we skip unlisted ones, consider as build: false, test: false
```

if `default_rules` is not set, we use the same behavior as before, i.e. build & test the officially supported targets under the specified IDF_PATH.
